directory: /mnt/music
library: ./musiclibrary.db
import:
  move: yes
  copy: no
  write: yes
  resume: yes
  autotag: yes
  default_action: apply
  duplicate_action: merge
  # incremental: yes
  languages: ["en", "pl", "fr", "de"]
  detail: yes
  log: ./log.txt
  # Nouvelle option pour gérer les VA
  group_albums: no # Force l'analyse piste par piste pour certains cas

# Configuration spéciale pour les VA
match:
  strong_rec_thresh: 0.40
  medium_rec_thresh: 0.25
  # Important : permet de traiter les morceaux individuellement
  singleton_thresh: 0.90
  ignored: missing_tracks


plugins: discogs bandcamp web inline mbsync fetchart edit duplicates info

web:
  host: 127.0.0.1.
  port: 8500

discogs:
  user_token: "hyDPKdjAJfqObOYfEPASiinZOTVzWxmSDXHQoMpK"
  source_weight: 0.0
  index_tracks: yes

item_fields:
  clean_title: |
    import unicodedata         
    # Normaliser les caractères Unicode         
    normalized = unicodedata.normalize('NFKD', title)         
    return normalized
  original_folder: |
    import os, re         
    path_str = os.fsdecode(path)         
    folder_name = os.path.basename(os.path.dirname(path_str))         
    # Nettoyer le nom du dossier         
    cleaned = folder_name.replace('VA', '').replace('V.A.', '').replace('va', '').replace('v.a.', '').strip()         
    # Mettre en forme titre (première lettre de chaque mot en majuscule)         
    cleaned = cleaned.title()         
    return cleaned if cleaned else folder_name

  folder_has_va: |
    import os
    path_str = os.fsdecode(path)
    folder_name = os.path.basename(os.path.dirname(path_str)).lower()
    return 'VA' in folder_name or 'V.A.' in folder_name or 'va' in folder_name or 'v.a.' in folder_name

paths:
  singleton: Non-Album/$artist/$title
  default: $artist/%if{$year,[$year] ,}$album/%if{$track,$track - ,}%if{$title,$title,%left{$path,50}}
  folder_has_va:true: Various Artists/%if{$album,$album,$original_folder}/%if{$track,$track-,}$artist-$title
  comp: Compilations/$album/%if{$track,$track-,''}$title

verbose: no

ui:
    color: yes
    colors:
        text_success: green
        text_warning: blue
        text_error: red
        text_highlight: blue
        text_highlight_minor: lightgray
        action_default: darkblue
        action: purple

fetchart:
  store_source: yes
  cover_names: cover
  art_filename: cover
